### ISSUE TITLE
Protobuf version is so old

### ISSUE THREAD

**Issue by iampawan** [FireStack-Lab/LaksaDart#3]
Hey, @neeboo can you also update to protobuf version to at least 1.0.1? Thanks

**Comment by neeboo** [comment]
**update:**
Seems it works, will release to pub.dev after making a series tests

well... the dart plugin for protobuf requires proto3
however the protobuf for Zilliqa only supports proto2...
Not sure whether it breaks

**Comment by neeboo** [comment]
> Hey, @neeboo can you also update to protobuf version to at least 1.0.1? Thanks

update version to [0.1.20-dev.2](https://pub.dev/packages/laksadart/versions/0.1.20-dev.2)
